In [1]:
import pandas as pd
import numpy as np

In [3]:
X = pd.read_csv('data/brain_counts.csv')
y = pd.read_csv('data/brain_metadata.csv')

In [4]:
X

,Unnamed: 0,0610005C13Rik,0610007C21Rik,0610007L01Rik,0610007N19Rik,0610007P08Rik,0610007P14Rik,0610007P22Rik,0610008F07Rik,0610009B14Rik,...,Zxdb,Zxdc,Zyg11a,Zyg11b,Zyx,Zzef1,Zzz3,a,l7Rn6,zsGreen_transgene
0,A1.B003290.3_38_F.1.1,0,125,16,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,54,0
1,A1.B003728.3_56_F.1.1,0,0,0,0,0,324,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,A1.MAA000560.3_10_M.1.1,0,348,0,0,0,5,0,0,0,...,0,0,0,0,0,195,0,0,113,0
3,A1.MAA000564.3_10_M.1.1,0,41,36,0,0,24,0,0,0,...,0,0,0,0,125,0,1,0,0,0
4,A1.MAA000923.3_9_M.1.1,0,53,0,0,0,0,0,0,0,...,0,0,0,81,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3396,P9.MAA000926.3_9_M.1.1,0,111,0,0,32,55,63,0,0,...,0,0,0,0,4,12,64,0,3,0
3397,P9.MAA000930.3_8_M.1.1,0,223,2,0,0,49,0,0,0,...,0,0,0,10,1,50,2,0,0,0
3398,P9.MAA000932.3_11_M.1.1,0,135,41,0,0,0,0,0,0,...,0,19,0,0,18,0,0,0,45,0
3399,P9.MAA000935.3_8_M.1.1,0,129,54,0,0,209,0,0,0,...,0,0,0,1,0,0,0,0,57,0
3400,P9.MAA001894.3_39_F.1.1,0,1,0,0,0,71,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
classes = {}
ontology = y['cell_ontology_class']
labels = []

i = 0
for ont in ontology:
    
    if not ont in classes:
        classes[ont] = i
        i += 1
    labels.append(classes[ont])

In [17]:
data = X.drop(columns=["Unnamed: 0", "zsGreen_transgene"])

In [19]:
data['label'] = labels

In [20]:
data

,0610005C13Rik,0610007C21Rik,0610007L01Rik,0610007N19Rik,0610007P08Rik,0610007P14Rik,0610007P22Rik,0610008F07Rik,0610009B14Rik,0610009B22Rik,...,Zxdb,Zxdc,Zyg11a,Zyg11b,Zyx,Zzef1,Zzz3,a,l7Rn6,label
0,0,125,16,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,54,0
1,0,0,0,0,0,324,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,348,0,0,0,5,0,0,0,0,...,0,0,0,0,0,195,0,0,113,1
3,0,41,36,0,0,24,0,0,0,14,...,0,0,0,0,125,0,1,0,0,2
4,0,53,0,0,0,0,0,0,0,0,...,0,0,0,81,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3396,0,111,0,0,32,55,63,0,0,0,...,0,0,0,0,4,12,64,0,3,4
3397,0,223,2,0,0,49,0,0,0,0,...,0,0,0,10,1,50,2,0,0,0
3398,0,135,41,0,0,0,0,0,0,0,...,0,19,0,0,18,0,0,0,45,2
3399,0,129,54,0,0,209,0,0,0,0,...,0,0,0,1,0,0,0,0,57,1
3400,0,1,0,0,0,71,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [23]:
data.to_csv('gene_expression.csv', index=False)